version: '3.8'

services:
  openldap:
    build: .
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=LDAPv3 Organization
      - LDAP_DOMAIN=duckdns.org
      - LDAP_ADMIN_PASSWORD=admin_password
      - LDAP_CONFIG_PASSWORD=config_password
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_VERIFY_CLIENT=try
    ports:
      - "389:389"   # LDAP
      - "636:636"   # LDAPS (LDAP over SSL μ•”νΈν™”)
    volumes:
      - ./data:/var/lib/ldap
      - ./config:/etc/ldap/slapd.d
      - ./certs:/etc/ssl/certs
      - ./init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif
    networks:
      ldap_network:
        ipv4_address: 158.180.82.84
    restart: unless-stopped

networks:
  ldap_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 158.180.82.0/24
          gateway: 158.180.82.1
